/* confdefs.h */
#define PACKAGE_NAME "ghpsdr3"
#define PACKAGE_TARNAME "ghpsdr3"
#define PACKAGE_VERSION "iw0hdv"
#define PACKAGE_STRING "ghpsdr3 iw0hdv"
#define PACKAGE_BUGREPORT "andrew att montefusco dott com"
#define PACKAGE_URL ""
#define PACKAGE "ghpsdr3"
#define VERSION "iw0hdv"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define HAVE_ARPA_INET_H 1
#define HAVE_FCNTL_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TIMEB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_PTHREAD_H 1
#define HAVE_PORTAUDIO_H 1
#define HAVE_FFTW3_H 1
#define HAVE_CODEC2_CODEC2_H 1
#define HAVE_PULSE_SIMPLE_H 1
#define HAVE_PULSE_ERROR_H 1
#define HAVE_USB_H 1
#define HAVE_JACK_JACK_H 1
#define HAVE_LIBCONFIG_H 1
#define HAVE_LIBUSB_H 1
#define HAVE_EVENT2_EVENT_H 1
#define HAVE_EVENT2_THREAD_H 1
#define HAVE_EVENT2_BUFFEREVENT_SSL_H 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_SAMPLERATE_H 1
#define HAVE_ORTP_ORTP_H 1
#define HAVE_RTCP_ORTP 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
#define HAVE_PTRDIFF_T 1
#define HAVE_FORK 1
#define HAVE_VFORK 1
#define HAVE_WORKING_VFORK 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 0
#define malloc rpl_malloc
#define HAVE_FLOOR 1
#define HAVE_FTIME 1
#define HAVE_GETCWD 1
#define HAVE_GETHOSTBYNAME 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_INET_NTOA 1
#define HAVE_MEMSET 1
#define HAVE_POW 1
#define HAVE_SELECT 1
#define HAVE_SOCKET 1
#define HAVE_SQRT 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
#define HAVE_STRTOL 1
