// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: r2t2gui.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_r2t2gui_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_r2t2gui_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_r2t2gui_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_r2t2gui_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_r2t2gui_2eproto;
namespace R2T2GuiProto {
class R2T2GuiMessage;
class R2T2GuiMessageDefaultTypeInternal;
extern R2T2GuiMessageDefaultTypeInternal _R2T2GuiMessage_default_instance_;
class R2T2GuiMessageAnswer;
class R2T2GuiMessageAnswerDefaultTypeInternal;
extern R2T2GuiMessageAnswerDefaultTypeInternal _R2T2GuiMessageAnswer_default_instance_;
}  // namespace R2T2GuiProto
PROTOBUF_NAMESPACE_OPEN
template<> ::R2T2GuiProto::R2T2GuiMessage* Arena::CreateMaybeMessage<::R2T2GuiProto::R2T2GuiMessage>(Arena*);
template<> ::R2T2GuiProto::R2T2GuiMessageAnswer* Arena::CreateMaybeMessage<::R2T2GuiProto::R2T2GuiMessageAnswer>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace R2T2GuiProto {

enum R2T2GuiMessage_Command : int {
  R2T2GuiMessage_Command_NONE = 0,
  R2T2GuiMessage_Command_STARTAUDIO = 1,
  R2T2GuiMessage_Command_STOPAUDIO = 2,
  R2T2GuiMessage_Command_REQFFT = 3,
  R2T2GuiMessage_Command_GETINFO = 4
};
bool R2T2GuiMessage_Command_IsValid(int value);
constexpr R2T2GuiMessage_Command R2T2GuiMessage_Command_Command_MIN = R2T2GuiMessage_Command_NONE;
constexpr R2T2GuiMessage_Command R2T2GuiMessage_Command_Command_MAX = R2T2GuiMessage_Command_GETINFO;
constexpr int R2T2GuiMessage_Command_Command_ARRAYSIZE = R2T2GuiMessage_Command_Command_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* R2T2GuiMessage_Command_descriptor();
template<typename T>
inline const std::string& R2T2GuiMessage_Command_Name(T enum_t_value) {
  static_assert(::std::is_same<T, R2T2GuiMessage_Command>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function R2T2GuiMessage_Command_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    R2T2GuiMessage_Command_descriptor(), enum_t_value);
}
inline bool R2T2GuiMessage_Command_Parse(
    const std::string& name, R2T2GuiMessage_Command* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<R2T2GuiMessage_Command>(
    R2T2GuiMessage_Command_descriptor(), name, value);
}
enum R2T2GuiMessage_Mode : int {
  R2T2GuiMessage_Mode_LSB = 0,
  R2T2GuiMessage_Mode_USB = 1,
  R2T2GuiMessage_Mode_DSB = 2,
  R2T2GuiMessage_Mode_CWL = 3,
  R2T2GuiMessage_Mode_CWU = 4,
  R2T2GuiMessage_Mode_FM = 5,
  R2T2GuiMessage_Mode_AM = 6,
  R2T2GuiMessage_Mode_DIGU = 7,
  R2T2GuiMessage_Mode_SPEC = 8,
  R2T2GuiMessage_Mode_DIGL = 9,
  R2T2GuiMessage_Mode_SAM = 10,
  R2T2GuiMessage_Mode_DRM = 11
};
bool R2T2GuiMessage_Mode_IsValid(int value);
constexpr R2T2GuiMessage_Mode R2T2GuiMessage_Mode_Mode_MIN = R2T2GuiMessage_Mode_LSB;
constexpr R2T2GuiMessage_Mode R2T2GuiMessage_Mode_Mode_MAX = R2T2GuiMessage_Mode_DRM;
constexpr int R2T2GuiMessage_Mode_Mode_ARRAYSIZE = R2T2GuiMessage_Mode_Mode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* R2T2GuiMessage_Mode_descriptor();
template<typename T>
inline const std::string& R2T2GuiMessage_Mode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, R2T2GuiMessage_Mode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function R2T2GuiMessage_Mode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    R2T2GuiMessage_Mode_descriptor(), enum_t_value);
}
inline bool R2T2GuiMessage_Mode_Parse(
    const std::string& name, R2T2GuiMessage_Mode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<R2T2GuiMessage_Mode>(
    R2T2GuiMessage_Mode_descriptor(), name, value);
}
enum R2T2GuiMessage_AGC : int {
  R2T2GuiMessage_AGC_fixed = 0,
  R2T2GuiMessage_AGC_slow = 1,
  R2T2GuiMessage_AGC_mid = 2,
  R2T2GuiMessage_AGC_fast = 3,
  R2T2GuiMessage_AGC_veryfast = 4
};
bool R2T2GuiMessage_AGC_IsValid(int value);
constexpr R2T2GuiMessage_AGC R2T2GuiMessage_AGC_AGC_MIN = R2T2GuiMessage_AGC_fixed;
constexpr R2T2GuiMessage_AGC R2T2GuiMessage_AGC_AGC_MAX = R2T2GuiMessage_AGC_veryfast;
constexpr int R2T2GuiMessage_AGC_AGC_ARRAYSIZE = R2T2GuiMessage_AGC_AGC_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* R2T2GuiMessage_AGC_descriptor();
template<typename T>
inline const std::string& R2T2GuiMessage_AGC_Name(T enum_t_value) {
  static_assert(::std::is_same<T, R2T2GuiMessage_AGC>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function R2T2GuiMessage_AGC_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    R2T2GuiMessage_AGC_descriptor(), enum_t_value);
}
inline bool R2T2GuiMessage_AGC_Parse(
    const std::string& name, R2T2GuiMessage_AGC* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<R2T2GuiMessage_AGC>(
    R2T2GuiMessage_AGC_descriptor(), name, value);
}
enum R2T2GuiMessageAnswer_Command : int {
  R2T2GuiMessageAnswer_Command_NONE = 0
};
bool R2T2GuiMessageAnswer_Command_IsValid(int value);
constexpr R2T2GuiMessageAnswer_Command R2T2GuiMessageAnswer_Command_Command_MIN = R2T2GuiMessageAnswer_Command_NONE;
constexpr R2T2GuiMessageAnswer_Command R2T2GuiMessageAnswer_Command_Command_MAX = R2T2GuiMessageAnswer_Command_NONE;
constexpr int R2T2GuiMessageAnswer_Command_Command_ARRAYSIZE = R2T2GuiMessageAnswer_Command_Command_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* R2T2GuiMessageAnswer_Command_descriptor();
template<typename T>
inline const std::string& R2T2GuiMessageAnswer_Command_Name(T enum_t_value) {
  static_assert(::std::is_same<T, R2T2GuiMessageAnswer_Command>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function R2T2GuiMessageAnswer_Command_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    R2T2GuiMessageAnswer_Command_descriptor(), enum_t_value);
}
inline bool R2T2GuiMessageAnswer_Command_Parse(
    const std::string& name, R2T2GuiMessageAnswer_Command* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<R2T2GuiMessageAnswer_Command>(
    R2T2GuiMessageAnswer_Command_descriptor(), name, value);
}
// ===================================================================

class R2T2GuiMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:R2T2GuiProto.R2T2GuiMessage) */ {
 public:
  R2T2GuiMessage();
  virtual ~R2T2GuiMessage();

  R2T2GuiMessage(const R2T2GuiMessage& from);
  R2T2GuiMessage(R2T2GuiMessage&& from) noexcept
    : R2T2GuiMessage() {
    *this = ::std::move(from);
  }

  inline R2T2GuiMessage& operator=(const R2T2GuiMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline R2T2GuiMessage& operator=(R2T2GuiMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const R2T2GuiMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const R2T2GuiMessage* internal_default_instance() {
    return reinterpret_cast<const R2T2GuiMessage*>(
               &_R2T2GuiMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(R2T2GuiMessage& a, R2T2GuiMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(R2T2GuiMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline R2T2GuiMessage* New() const final {
    return CreateMaybeMessage<R2T2GuiMessage>(nullptr);
  }

  R2T2GuiMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<R2T2GuiMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const R2T2GuiMessage& from);
  void MergeFrom(const R2T2GuiMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(R2T2GuiMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "R2T2GuiProto.R2T2GuiMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_r2t2gui_2eproto);
    return ::descriptor_table_r2t2gui_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef R2T2GuiMessage_Command Command;
  static constexpr Command NONE =
    R2T2GuiMessage_Command_NONE;
  static constexpr Command STARTAUDIO =
    R2T2GuiMessage_Command_STARTAUDIO;
  static constexpr Command STOPAUDIO =
    R2T2GuiMessage_Command_STOPAUDIO;
  static constexpr Command REQFFT =
    R2T2GuiMessage_Command_REQFFT;
  static constexpr Command GETINFO =
    R2T2GuiMessage_Command_GETINFO;
  static inline bool Command_IsValid(int value) {
    return R2T2GuiMessage_Command_IsValid(value);
  }
  static constexpr Command Command_MIN =
    R2T2GuiMessage_Command_Command_MIN;
  static constexpr Command Command_MAX =
    R2T2GuiMessage_Command_Command_MAX;
  static constexpr int Command_ARRAYSIZE =
    R2T2GuiMessage_Command_Command_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Command_descriptor() {
    return R2T2GuiMessage_Command_descriptor();
  }
  template<typename T>
  static inline const std::string& Command_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Command>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Command_Name.");
    return R2T2GuiMessage_Command_Name(enum_t_value);
  }
  static inline bool Command_Parse(const std::string& name,
      Command* value) {
    return R2T2GuiMessage_Command_Parse(name, value);
  }

  typedef R2T2GuiMessage_Mode Mode;
  static constexpr Mode LSB =
    R2T2GuiMessage_Mode_LSB;
  static constexpr Mode USB =
    R2T2GuiMessage_Mode_USB;
  static constexpr Mode DSB =
    R2T2GuiMessage_Mode_DSB;
  static constexpr Mode CWL =
    R2T2GuiMessage_Mode_CWL;
  static constexpr Mode CWU =
    R2T2GuiMessage_Mode_CWU;
  static constexpr Mode FM =
    R2T2GuiMessage_Mode_FM;
  static constexpr Mode AM =
    R2T2GuiMessage_Mode_AM;
  static constexpr Mode DIGU =
    R2T2GuiMessage_Mode_DIGU;
  static constexpr Mode SPEC =
    R2T2GuiMessage_Mode_SPEC;
  static constexpr Mode DIGL =
    R2T2GuiMessage_Mode_DIGL;
  static constexpr Mode SAM =
    R2T2GuiMessage_Mode_SAM;
  static constexpr Mode DRM =
    R2T2GuiMessage_Mode_DRM;
  static inline bool Mode_IsValid(int value) {
    return R2T2GuiMessage_Mode_IsValid(value);
  }
  static constexpr Mode Mode_MIN =
    R2T2GuiMessage_Mode_Mode_MIN;
  static constexpr Mode Mode_MAX =
    R2T2GuiMessage_Mode_Mode_MAX;
  static constexpr int Mode_ARRAYSIZE =
    R2T2GuiMessage_Mode_Mode_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Mode_descriptor() {
    return R2T2GuiMessage_Mode_descriptor();
  }
  template<typename T>
  static inline const std::string& Mode_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Mode>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Mode_Name.");
    return R2T2GuiMessage_Mode_Name(enum_t_value);
  }
  static inline bool Mode_Parse(const std::string& name,
      Mode* value) {
    return R2T2GuiMessage_Mode_Parse(name, value);
  }

  typedef R2T2GuiMessage_AGC AGC;
  static constexpr AGC fixed =
    R2T2GuiMessage_AGC_fixed;
  static constexpr AGC slow =
    R2T2GuiMessage_AGC_slow;
  static constexpr AGC mid =
    R2T2GuiMessage_AGC_mid;
  static constexpr AGC fast =
    R2T2GuiMessage_AGC_fast;
  static constexpr AGC veryfast =
    R2T2GuiMessage_AGC_veryfast;
  static inline bool AGC_IsValid(int value) {
    return R2T2GuiMessage_AGC_IsValid(value);
  }
  static constexpr AGC AGC_MIN =
    R2T2GuiMessage_AGC_AGC_MIN;
  static constexpr AGC AGC_MAX =
    R2T2GuiMessage_AGC_AGC_MAX;
  static constexpr int AGC_ARRAYSIZE =
    R2T2GuiMessage_AGC_AGC_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  AGC_descriptor() {
    return R2T2GuiMessage_AGC_descriptor();
  }
  template<typename T>
  static inline const std::string& AGC_Name(T enum_t_value) {
    static_assert(::std::is_same<T, AGC>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function AGC_Name.");
    return R2T2GuiMessage_AGC_Name(enum_t_value);
  }
  static inline bool AGC_Parse(const std::string& name,
      AGC* value) {
    return R2T2GuiMessage_AGC_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTxDataFieldNumber = 2,
    kVersionFieldNumber = 13,
    kRxFreqFieldNumber = 3,
    kCommandFieldNumber = 1,
    kFftRateFieldNumber = 5,
    kTxFreqFieldNumber = 4,
    kFftSizeFieldNumber = 6,
    kModeFieldNumber = 7,
    kGainFieldNumber = 8,
    kAntennaFieldNumber = 9,
    kAgcFieldNumber = 10,
    kFilterLoFieldNumber = 11,
    kFilterHiFieldNumber = 12,
    kNotchFieldNumber = 14,
    kNoiseFieldNumber = 15,
  };
  // optional bytes txData = 2;
  bool has_txdata() const;
  private:
  bool _internal_has_txdata() const;
  public:
  void clear_txdata();
  const std::string& txdata() const;
  void set_txdata(const std::string& value);
  void set_txdata(std::string&& value);
  void set_txdata(const char* value);
  void set_txdata(const void* value, size_t size);
  std::string* mutable_txdata();
  std::string* release_txdata();
  void set_allocated_txdata(std::string* txdata);
  private:
  const std::string& _internal_txdata() const;
  void _internal_set_txdata(const std::string& value);
  std::string* _internal_mutable_txdata();
  public:

  // optional string version = 13;
  bool has_version() const;
  private:
  bool _internal_has_version() const;
  public:
  void clear_version();
  const std::string& version() const;
  void set_version(const std::string& value);
  void set_version(std::string&& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  std::string* mutable_version();
  std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // optional uint64 rxFreq = 3;
  bool has_rxfreq() const;
  private:
  bool _internal_has_rxfreq() const;
  public:
  void clear_rxfreq();
  ::PROTOBUF_NAMESPACE_ID::uint64 rxfreq() const;
  void set_rxfreq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_rxfreq() const;
  void _internal_set_rxfreq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional .R2T2GuiProto.R2T2GuiMessage.Command command = 1;
  bool has_command() const;
  private:
  bool _internal_has_command() const;
  public:
  void clear_command();
  ::R2T2GuiProto::R2T2GuiMessage_Command command() const;
  void set_command(::R2T2GuiProto::R2T2GuiMessage_Command value);
  private:
  ::R2T2GuiProto::R2T2GuiMessage_Command _internal_command() const;
  void _internal_set_command(::R2T2GuiProto::R2T2GuiMessage_Command value);
  public:

  // optional uint32 fftRate = 5;
  bool has_fftrate() const;
  private:
  bool _internal_has_fftrate() const;
  public:
  void clear_fftrate();
  ::PROTOBUF_NAMESPACE_ID::uint32 fftrate() const;
  void set_fftrate(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_fftrate() const;
  void _internal_set_fftrate(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint64 txFreq = 4;
  bool has_txfreq() const;
  private:
  bool _internal_has_txfreq() const;
  public:
  void clear_txfreq();
  ::PROTOBUF_NAMESPACE_ID::uint64 txfreq() const;
  void set_txfreq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_txfreq() const;
  void _internal_set_txfreq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint32 fftSize = 6;
  bool has_fftsize() const;
  private:
  bool _internal_has_fftsize() const;
  public:
  void clear_fftsize();
  ::PROTOBUF_NAMESPACE_ID::uint32 fftsize() const;
  void set_fftsize(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_fftsize() const;
  void _internal_set_fftsize(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional .R2T2GuiProto.R2T2GuiMessage.Mode mode = 7;
  bool has_mode() const;
  private:
  bool _internal_has_mode() const;
  public:
  void clear_mode();
  ::R2T2GuiProto::R2T2GuiMessage_Mode mode() const;
  void set_mode(::R2T2GuiProto::R2T2GuiMessage_Mode value);
  private:
  ::R2T2GuiProto::R2T2GuiMessage_Mode _internal_mode() const;
  void _internal_set_mode(::R2T2GuiProto::R2T2GuiMessage_Mode value);
  public:

  // optional int32 gain = 8;
  bool has_gain() const;
  private:
  bool _internal_has_gain() const;
  public:
  void clear_gain();
  ::PROTOBUF_NAMESPACE_ID::int32 gain() const;
  void set_gain(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_gain() const;
  void _internal_set_gain(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional uint32 antenna = 9;
  bool has_antenna() const;
  private:
  bool _internal_has_antenna() const;
  public:
  void clear_antenna();
  ::PROTOBUF_NAMESPACE_ID::uint32 antenna() const;
  void set_antenna(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_antenna() const;
  void _internal_set_antenna(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional .R2T2GuiProto.R2T2GuiMessage.AGC agc = 10;
  bool has_agc() const;
  private:
  bool _internal_has_agc() const;
  public:
  void clear_agc();
  ::R2T2GuiProto::R2T2GuiMessage_AGC agc() const;
  void set_agc(::R2T2GuiProto::R2T2GuiMessage_AGC value);
  private:
  ::R2T2GuiProto::R2T2GuiMessage_AGC _internal_agc() const;
  void _internal_set_agc(::R2T2GuiProto::R2T2GuiMessage_AGC value);
  public:

  // optional int32 filterLo = 11;
  bool has_filterlo() const;
  private:
  bool _internal_has_filterlo() const;
  public:
  void clear_filterlo();
  ::PROTOBUF_NAMESPACE_ID::int32 filterlo() const;
  void set_filterlo(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_filterlo() const;
  void _internal_set_filterlo(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 filterHi = 12;
  bool has_filterhi() const;
  private:
  bool _internal_has_filterhi() const;
  public:
  void clear_filterhi();
  ::PROTOBUF_NAMESPACE_ID::int32 filterhi() const;
  void set_filterhi(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_filterhi() const;
  void _internal_set_filterhi(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 notch = 14;
  bool has_notch() const;
  private:
  bool _internal_has_notch() const;
  public:
  void clear_notch();
  ::PROTOBUF_NAMESPACE_ID::int32 notch() const;
  void set_notch(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_notch() const;
  void _internal_set_notch(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 noise = 15;
  bool has_noise() const;
  private:
  bool _internal_has_noise() const;
  public:
  void clear_noise();
  ::PROTOBUF_NAMESPACE_ID::int32 noise() const;
  void set_noise(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_noise() const;
  void _internal_set_noise(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:R2T2GuiProto.R2T2GuiMessage)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr txdata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  ::PROTOBUF_NAMESPACE_ID::uint64 rxfreq_;
  int command_;
  ::PROTOBUF_NAMESPACE_ID::uint32 fftrate_;
  ::PROTOBUF_NAMESPACE_ID::uint64 txfreq_;
  ::PROTOBUF_NAMESPACE_ID::uint32 fftsize_;
  int mode_;
  ::PROTOBUF_NAMESPACE_ID::int32 gain_;
  ::PROTOBUF_NAMESPACE_ID::uint32 antenna_;
  int agc_;
  ::PROTOBUF_NAMESPACE_ID::int32 filterlo_;
  ::PROTOBUF_NAMESPACE_ID::int32 filterhi_;
  ::PROTOBUF_NAMESPACE_ID::int32 notch_;
  ::PROTOBUF_NAMESPACE_ID::int32 noise_;
  friend struct ::TableStruct_r2t2gui_2eproto;
};
// -------------------------------------------------------------------

class R2T2GuiMessageAnswer :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:R2T2GuiProto.R2T2GuiMessageAnswer) */ {
 public:
  R2T2GuiMessageAnswer();
  virtual ~R2T2GuiMessageAnswer();

  R2T2GuiMessageAnswer(const R2T2GuiMessageAnswer& from);
  R2T2GuiMessageAnswer(R2T2GuiMessageAnswer&& from) noexcept
    : R2T2GuiMessageAnswer() {
    *this = ::std::move(from);
  }

  inline R2T2GuiMessageAnswer& operator=(const R2T2GuiMessageAnswer& from) {
    CopyFrom(from);
    return *this;
  }
  inline R2T2GuiMessageAnswer& operator=(R2T2GuiMessageAnswer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const R2T2GuiMessageAnswer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const R2T2GuiMessageAnswer* internal_default_instance() {
    return reinterpret_cast<const R2T2GuiMessageAnswer*>(
               &_R2T2GuiMessageAnswer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(R2T2GuiMessageAnswer& a, R2T2GuiMessageAnswer& b) {
    a.Swap(&b);
  }
  inline void Swap(R2T2GuiMessageAnswer* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline R2T2GuiMessageAnswer* New() const final {
    return CreateMaybeMessage<R2T2GuiMessageAnswer>(nullptr);
  }

  R2T2GuiMessageAnswer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<R2T2GuiMessageAnswer>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const R2T2GuiMessageAnswer& from);
  void MergeFrom(const R2T2GuiMessageAnswer& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(R2T2GuiMessageAnswer* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "R2T2GuiProto.R2T2GuiMessageAnswer";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_r2t2gui_2eproto);
    return ::descriptor_table_r2t2gui_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef R2T2GuiMessageAnswer_Command Command;
  static constexpr Command NONE =
    R2T2GuiMessageAnswer_Command_NONE;
  static inline bool Command_IsValid(int value) {
    return R2T2GuiMessageAnswer_Command_IsValid(value);
  }
  static constexpr Command Command_MIN =
    R2T2GuiMessageAnswer_Command_Command_MIN;
  static constexpr Command Command_MAX =
    R2T2GuiMessageAnswer_Command_Command_MAX;
  static constexpr int Command_ARRAYSIZE =
    R2T2GuiMessageAnswer_Command_Command_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Command_descriptor() {
    return R2T2GuiMessageAnswer_Command_descriptor();
  }
  template<typename T>
  static inline const std::string& Command_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Command>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Command_Name.");
    return R2T2GuiMessageAnswer_Command_Name(enum_t_value);
  }
  static inline bool Command_Parse(const std::string& name,
      Command* value) {
    return R2T2GuiMessageAnswer_Command_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kRxDataFieldNumber = 2,
    kFftDataFieldNumber = 3,
    kVersionFieldNumber = 6,
    kCommandFieldNumber = 1,
    kTxDataAckFieldNumber = 4,
    kRssiFieldNumber = 5,
    kFftRateFieldNumber = 7,
    kGainFieldNumber = 8,
  };
  // optional bytes rxData = 2;
  bool has_rxdata() const;
  private:
  bool _internal_has_rxdata() const;
  public:
  void clear_rxdata();
  const std::string& rxdata() const;
  void set_rxdata(const std::string& value);
  void set_rxdata(std::string&& value);
  void set_rxdata(const char* value);
  void set_rxdata(const void* value, size_t size);
  std::string* mutable_rxdata();
  std::string* release_rxdata();
  void set_allocated_rxdata(std::string* rxdata);
  private:
  const std::string& _internal_rxdata() const;
  void _internal_set_rxdata(const std::string& value);
  std::string* _internal_mutable_rxdata();
  public:

  // optional bytes fftData = 3;
  bool has_fftdata() const;
  private:
  bool _internal_has_fftdata() const;
  public:
  void clear_fftdata();
  const std::string& fftdata() const;
  void set_fftdata(const std::string& value);
  void set_fftdata(std::string&& value);
  void set_fftdata(const char* value);
  void set_fftdata(const void* value, size_t size);
  std::string* mutable_fftdata();
  std::string* release_fftdata();
  void set_allocated_fftdata(std::string* fftdata);
  private:
  const std::string& _internal_fftdata() const;
  void _internal_set_fftdata(const std::string& value);
  std::string* _internal_mutable_fftdata();
  public:

  // optional string version = 6;
  bool has_version() const;
  private:
  bool _internal_has_version() const;
  public:
  void clear_version();
  const std::string& version() const;
  void set_version(const std::string& value);
  void set_version(std::string&& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  std::string* mutable_version();
  std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // optional .R2T2GuiProto.R2T2GuiMessageAnswer.Command command = 1;
  bool has_command() const;
  private:
  bool _internal_has_command() const;
  public:
  void clear_command();
  ::R2T2GuiProto::R2T2GuiMessageAnswer_Command command() const;
  void set_command(::R2T2GuiProto::R2T2GuiMessageAnswer_Command value);
  private:
  ::R2T2GuiProto::R2T2GuiMessageAnswer_Command _internal_command() const;
  void _internal_set_command(::R2T2GuiProto::R2T2GuiMessageAnswer_Command value);
  public:

  // optional uint32 txDataAck = 4;
  bool has_txdataack() const;
  private:
  bool _internal_has_txdataack() const;
  public:
  void clear_txdataack();
  ::PROTOBUF_NAMESPACE_ID::uint32 txdataack() const;
  void set_txdataack(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_txdataack() const;
  void _internal_set_txdataack(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional double rssi = 5;
  bool has_rssi() const;
  private:
  bool _internal_has_rssi() const;
  public:
  void clear_rssi();
  double rssi() const;
  void set_rssi(double value);
  private:
  double _internal_rssi() const;
  void _internal_set_rssi(double value);
  public:

  // optional uint32 fftRate = 7;
  bool has_fftrate() const;
  private:
  bool _internal_has_fftrate() const;
  public:
  void clear_fftrate();
  ::PROTOBUF_NAMESPACE_ID::uint32 fftrate() const;
  void set_fftrate(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_fftrate() const;
  void _internal_set_fftrate(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional int32 gain = 8;
  bool has_gain() const;
  private:
  bool _internal_has_gain() const;
  public:
  void clear_gain();
  ::PROTOBUF_NAMESPACE_ID::int32 gain() const;
  void set_gain(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_gain() const;
  void _internal_set_gain(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:R2T2GuiProto.R2T2GuiMessageAnswer)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rxdata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fftdata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  int command_;
  ::PROTOBUF_NAMESPACE_ID::uint32 txdataack_;
  double rssi_;
  ::PROTOBUF_NAMESPACE_ID::uint32 fftrate_;
  ::PROTOBUF_NAMESPACE_ID::int32 gain_;
  friend struct ::TableStruct_r2t2gui_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// R2T2GuiMessage

// optional .R2T2GuiProto.R2T2GuiMessage.Command command = 1;
inline bool R2T2GuiMessage::_internal_has_command() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_command() const {
  return _internal_has_command();
}
inline void R2T2GuiMessage::clear_command() {
  command_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::R2T2GuiProto::R2T2GuiMessage_Command R2T2GuiMessage::_internal_command() const {
  return static_cast< ::R2T2GuiProto::R2T2GuiMessage_Command >(command_);
}
inline ::R2T2GuiProto::R2T2GuiMessage_Command R2T2GuiMessage::command() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.command)
  return _internal_command();
}
inline void R2T2GuiMessage::_internal_set_command(::R2T2GuiProto::R2T2GuiMessage_Command value) {
  assert(::R2T2GuiProto::R2T2GuiMessage_Command_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  command_ = value;
}
inline void R2T2GuiMessage::set_command(::R2T2GuiProto::R2T2GuiMessage_Command value) {
  _internal_set_command(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.command)
}

// optional bytes txData = 2;
inline bool R2T2GuiMessage::_internal_has_txdata() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_txdata() const {
  return _internal_has_txdata();
}
inline void R2T2GuiMessage::clear_txdata() {
  txdata_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& R2T2GuiMessage::txdata() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.txData)
  return _internal_txdata();
}
inline void R2T2GuiMessage::set_txdata(const std::string& value) {
  _internal_set_txdata(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.txData)
}
inline std::string* R2T2GuiMessage::mutable_txdata() {
  // @@protoc_insertion_point(field_mutable:R2T2GuiProto.R2T2GuiMessage.txData)
  return _internal_mutable_txdata();
}
inline const std::string& R2T2GuiMessage::_internal_txdata() const {
  return txdata_.GetNoArena();
}
inline void R2T2GuiMessage::_internal_set_txdata(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  txdata_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void R2T2GuiMessage::set_txdata(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  txdata_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:R2T2GuiProto.R2T2GuiMessage.txData)
}
inline void R2T2GuiMessage::set_txdata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  txdata_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:R2T2GuiProto.R2T2GuiMessage.txData)
}
inline void R2T2GuiMessage::set_txdata(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  txdata_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:R2T2GuiProto.R2T2GuiMessage.txData)
}
inline std::string* R2T2GuiMessage::_internal_mutable_txdata() {
  _has_bits_[0] |= 0x00000001u;
  return txdata_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* R2T2GuiMessage::release_txdata() {
  // @@protoc_insertion_point(field_release:R2T2GuiProto.R2T2GuiMessage.txData)
  if (!_internal_has_txdata()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return txdata_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void R2T2GuiMessage::set_allocated_txdata(std::string* txdata) {
  if (txdata != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  txdata_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), txdata);
  // @@protoc_insertion_point(field_set_allocated:R2T2GuiProto.R2T2GuiMessage.txData)
}

// optional uint64 rxFreq = 3;
inline bool R2T2GuiMessage::_internal_has_rxfreq() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_rxfreq() const {
  return _internal_has_rxfreq();
}
inline void R2T2GuiMessage::clear_rxfreq() {
  rxfreq_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 R2T2GuiMessage::_internal_rxfreq() const {
  return rxfreq_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 R2T2GuiMessage::rxfreq() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.rxFreq)
  return _internal_rxfreq();
}
inline void R2T2GuiMessage::_internal_set_rxfreq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  rxfreq_ = value;
}
inline void R2T2GuiMessage::set_rxfreq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_rxfreq(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.rxFreq)
}

// optional uint64 txFreq = 4;
inline bool R2T2GuiMessage::_internal_has_txfreq() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_txfreq() const {
  return _internal_has_txfreq();
}
inline void R2T2GuiMessage::clear_txfreq() {
  txfreq_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 R2T2GuiMessage::_internal_txfreq() const {
  return txfreq_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 R2T2GuiMessage::txfreq() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.txFreq)
  return _internal_txfreq();
}
inline void R2T2GuiMessage::_internal_set_txfreq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000020u;
  txfreq_ = value;
}
inline void R2T2GuiMessage::set_txfreq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_txfreq(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.txFreq)
}

// optional uint32 fftRate = 5;
inline bool R2T2GuiMessage::_internal_has_fftrate() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_fftrate() const {
  return _internal_has_fftrate();
}
inline void R2T2GuiMessage::clear_fftrate() {
  fftrate_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessage::_internal_fftrate() const {
  return fftrate_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessage::fftrate() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.fftRate)
  return _internal_fftrate();
}
inline void R2T2GuiMessage::_internal_set_fftrate(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  fftrate_ = value;
}
inline void R2T2GuiMessage::set_fftrate(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_fftrate(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.fftRate)
}

// optional uint32 fftSize = 6;
inline bool R2T2GuiMessage::_internal_has_fftsize() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_fftsize() const {
  return _internal_has_fftsize();
}
inline void R2T2GuiMessage::clear_fftsize() {
  fftsize_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessage::_internal_fftsize() const {
  return fftsize_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessage::fftsize() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.fftSize)
  return _internal_fftsize();
}
inline void R2T2GuiMessage::_internal_set_fftsize(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  fftsize_ = value;
}
inline void R2T2GuiMessage::set_fftsize(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_fftsize(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.fftSize)
}

// optional .R2T2GuiProto.R2T2GuiMessage.Mode mode = 7;
inline bool R2T2GuiMessage::_internal_has_mode() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_mode() const {
  return _internal_has_mode();
}
inline void R2T2GuiMessage::clear_mode() {
  mode_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::R2T2GuiProto::R2T2GuiMessage_Mode R2T2GuiMessage::_internal_mode() const {
  return static_cast< ::R2T2GuiProto::R2T2GuiMessage_Mode >(mode_);
}
inline ::R2T2GuiProto::R2T2GuiMessage_Mode R2T2GuiMessage::mode() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.mode)
  return _internal_mode();
}
inline void R2T2GuiMessage::_internal_set_mode(::R2T2GuiProto::R2T2GuiMessage_Mode value) {
  assert(::R2T2GuiProto::R2T2GuiMessage_Mode_IsValid(value));
  _has_bits_[0] |= 0x00000080u;
  mode_ = value;
}
inline void R2T2GuiMessage::set_mode(::R2T2GuiProto::R2T2GuiMessage_Mode value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.mode)
}

// optional int32 gain = 8;
inline bool R2T2GuiMessage::_internal_has_gain() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_gain() const {
  return _internal_has_gain();
}
inline void R2T2GuiMessage::clear_gain() {
  gain_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::_internal_gain() const {
  return gain_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::gain() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.gain)
  return _internal_gain();
}
inline void R2T2GuiMessage::_internal_set_gain(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000100u;
  gain_ = value;
}
inline void R2T2GuiMessage::set_gain(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_gain(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.gain)
}

// optional uint32 antenna = 9;
inline bool R2T2GuiMessage::_internal_has_antenna() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_antenna() const {
  return _internal_has_antenna();
}
inline void R2T2GuiMessage::clear_antenna() {
  antenna_ = 0u;
  _has_bits_[0] &= ~0x00000200u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessage::_internal_antenna() const {
  return antenna_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessage::antenna() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.antenna)
  return _internal_antenna();
}
inline void R2T2GuiMessage::_internal_set_antenna(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000200u;
  antenna_ = value;
}
inline void R2T2GuiMessage::set_antenna(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_antenna(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.antenna)
}

// optional .R2T2GuiProto.R2T2GuiMessage.AGC agc = 10;
inline bool R2T2GuiMessage::_internal_has_agc() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_agc() const {
  return _internal_has_agc();
}
inline void R2T2GuiMessage::clear_agc() {
  agc_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline ::R2T2GuiProto::R2T2GuiMessage_AGC R2T2GuiMessage::_internal_agc() const {
  return static_cast< ::R2T2GuiProto::R2T2GuiMessage_AGC >(agc_);
}
inline ::R2T2GuiProto::R2T2GuiMessage_AGC R2T2GuiMessage::agc() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.agc)
  return _internal_agc();
}
inline void R2T2GuiMessage::_internal_set_agc(::R2T2GuiProto::R2T2GuiMessage_AGC value) {
  assert(::R2T2GuiProto::R2T2GuiMessage_AGC_IsValid(value));
  _has_bits_[0] |= 0x00000400u;
  agc_ = value;
}
inline void R2T2GuiMessage::set_agc(::R2T2GuiProto::R2T2GuiMessage_AGC value) {
  _internal_set_agc(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.agc)
}

// optional int32 filterLo = 11;
inline bool R2T2GuiMessage::_internal_has_filterlo() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_filterlo() const {
  return _internal_has_filterlo();
}
inline void R2T2GuiMessage::clear_filterlo() {
  filterlo_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::_internal_filterlo() const {
  return filterlo_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::filterlo() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.filterLo)
  return _internal_filterlo();
}
inline void R2T2GuiMessage::_internal_set_filterlo(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000800u;
  filterlo_ = value;
}
inline void R2T2GuiMessage::set_filterlo(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_filterlo(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.filterLo)
}

// optional int32 filterHi = 12;
inline bool R2T2GuiMessage::_internal_has_filterhi() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_filterhi() const {
  return _internal_has_filterhi();
}
inline void R2T2GuiMessage::clear_filterhi() {
  filterhi_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::_internal_filterhi() const {
  return filterhi_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::filterhi() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.filterHi)
  return _internal_filterhi();
}
inline void R2T2GuiMessage::_internal_set_filterhi(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00001000u;
  filterhi_ = value;
}
inline void R2T2GuiMessage::set_filterhi(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_filterhi(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.filterHi)
}

// optional string version = 13;
inline bool R2T2GuiMessage::_internal_has_version() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_version() const {
  return _internal_has_version();
}
inline void R2T2GuiMessage::clear_version() {
  version_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& R2T2GuiMessage::version() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.version)
  return _internal_version();
}
inline void R2T2GuiMessage::set_version(const std::string& value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.version)
}
inline std::string* R2T2GuiMessage::mutable_version() {
  // @@protoc_insertion_point(field_mutable:R2T2GuiProto.R2T2GuiMessage.version)
  return _internal_mutable_version();
}
inline const std::string& R2T2GuiMessage::_internal_version() const {
  return version_.GetNoArena();
}
inline void R2T2GuiMessage::_internal_set_version(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void R2T2GuiMessage::set_version(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  version_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:R2T2GuiProto.R2T2GuiMessage.version)
}
inline void R2T2GuiMessage::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:R2T2GuiProto.R2T2GuiMessage.version)
}
inline void R2T2GuiMessage::set_version(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:R2T2GuiProto.R2T2GuiMessage.version)
}
inline std::string* R2T2GuiMessage::_internal_mutable_version() {
  _has_bits_[0] |= 0x00000002u;
  return version_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* R2T2GuiMessage::release_version() {
  // @@protoc_insertion_point(field_release:R2T2GuiProto.R2T2GuiMessage.version)
  if (!_internal_has_version()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return version_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void R2T2GuiMessage::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  version_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:R2T2GuiProto.R2T2GuiMessage.version)
}

// optional int32 notch = 14;
inline bool R2T2GuiMessage::_internal_has_notch() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_notch() const {
  return _internal_has_notch();
}
inline void R2T2GuiMessage::clear_notch() {
  notch_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::_internal_notch() const {
  return notch_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::notch() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.notch)
  return _internal_notch();
}
inline void R2T2GuiMessage::_internal_set_notch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00002000u;
  notch_ = value;
}
inline void R2T2GuiMessage::set_notch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_notch(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.notch)
}

// optional int32 noise = 15;
inline bool R2T2GuiMessage::_internal_has_noise() const {
  bool value = (_has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool R2T2GuiMessage::has_noise() const {
  return _internal_has_noise();
}
inline void R2T2GuiMessage::clear_noise() {
  noise_ = 0;
  _has_bits_[0] &= ~0x00004000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::_internal_noise() const {
  return noise_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessage::noise() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessage.noise)
  return _internal_noise();
}
inline void R2T2GuiMessage::_internal_set_noise(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00004000u;
  noise_ = value;
}
inline void R2T2GuiMessage::set_noise(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_noise(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessage.noise)
}

// -------------------------------------------------------------------

// R2T2GuiMessageAnswer

// optional .R2T2GuiProto.R2T2GuiMessageAnswer.Command command = 1;
inline bool R2T2GuiMessageAnswer::_internal_has_command() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool R2T2GuiMessageAnswer::has_command() const {
  return _internal_has_command();
}
inline void R2T2GuiMessageAnswer::clear_command() {
  command_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::R2T2GuiProto::R2T2GuiMessageAnswer_Command R2T2GuiMessageAnswer::_internal_command() const {
  return static_cast< ::R2T2GuiProto::R2T2GuiMessageAnswer_Command >(command_);
}
inline ::R2T2GuiProto::R2T2GuiMessageAnswer_Command R2T2GuiMessageAnswer::command() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessageAnswer.command)
  return _internal_command();
}
inline void R2T2GuiMessageAnswer::_internal_set_command(::R2T2GuiProto::R2T2GuiMessageAnswer_Command value) {
  assert(::R2T2GuiProto::R2T2GuiMessageAnswer_Command_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  command_ = value;
}
inline void R2T2GuiMessageAnswer::set_command(::R2T2GuiProto::R2T2GuiMessageAnswer_Command value) {
  _internal_set_command(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessageAnswer.command)
}

// optional bytes rxData = 2;
inline bool R2T2GuiMessageAnswer::_internal_has_rxdata() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool R2T2GuiMessageAnswer::has_rxdata() const {
  return _internal_has_rxdata();
}
inline void R2T2GuiMessageAnswer::clear_rxdata() {
  rxdata_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& R2T2GuiMessageAnswer::rxdata() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessageAnswer.rxData)
  return _internal_rxdata();
}
inline void R2T2GuiMessageAnswer::set_rxdata(const std::string& value) {
  _internal_set_rxdata(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessageAnswer.rxData)
}
inline std::string* R2T2GuiMessageAnswer::mutable_rxdata() {
  // @@protoc_insertion_point(field_mutable:R2T2GuiProto.R2T2GuiMessageAnswer.rxData)
  return _internal_mutable_rxdata();
}
inline const std::string& R2T2GuiMessageAnswer::_internal_rxdata() const {
  return rxdata_.GetNoArena();
}
inline void R2T2GuiMessageAnswer::_internal_set_rxdata(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  rxdata_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void R2T2GuiMessageAnswer::set_rxdata(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  rxdata_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:R2T2GuiProto.R2T2GuiMessageAnswer.rxData)
}
inline void R2T2GuiMessageAnswer::set_rxdata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  rxdata_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:R2T2GuiProto.R2T2GuiMessageAnswer.rxData)
}
inline void R2T2GuiMessageAnswer::set_rxdata(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  rxdata_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:R2T2GuiProto.R2T2GuiMessageAnswer.rxData)
}
inline std::string* R2T2GuiMessageAnswer::_internal_mutable_rxdata() {
  _has_bits_[0] |= 0x00000001u;
  return rxdata_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* R2T2GuiMessageAnswer::release_rxdata() {
  // @@protoc_insertion_point(field_release:R2T2GuiProto.R2T2GuiMessageAnswer.rxData)
  if (!_internal_has_rxdata()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return rxdata_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void R2T2GuiMessageAnswer::set_allocated_rxdata(std::string* rxdata) {
  if (rxdata != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  rxdata_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), rxdata);
  // @@protoc_insertion_point(field_set_allocated:R2T2GuiProto.R2T2GuiMessageAnswer.rxData)
}

// optional bytes fftData = 3;
inline bool R2T2GuiMessageAnswer::_internal_has_fftdata() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool R2T2GuiMessageAnswer::has_fftdata() const {
  return _internal_has_fftdata();
}
inline void R2T2GuiMessageAnswer::clear_fftdata() {
  fftdata_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& R2T2GuiMessageAnswer::fftdata() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessageAnswer.fftData)
  return _internal_fftdata();
}
inline void R2T2GuiMessageAnswer::set_fftdata(const std::string& value) {
  _internal_set_fftdata(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessageAnswer.fftData)
}
inline std::string* R2T2GuiMessageAnswer::mutable_fftdata() {
  // @@protoc_insertion_point(field_mutable:R2T2GuiProto.R2T2GuiMessageAnswer.fftData)
  return _internal_mutable_fftdata();
}
inline const std::string& R2T2GuiMessageAnswer::_internal_fftdata() const {
  return fftdata_.GetNoArena();
}
inline void R2T2GuiMessageAnswer::_internal_set_fftdata(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  fftdata_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void R2T2GuiMessageAnswer::set_fftdata(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  fftdata_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:R2T2GuiProto.R2T2GuiMessageAnswer.fftData)
}
inline void R2T2GuiMessageAnswer::set_fftdata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  fftdata_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:R2T2GuiProto.R2T2GuiMessageAnswer.fftData)
}
inline void R2T2GuiMessageAnswer::set_fftdata(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  fftdata_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:R2T2GuiProto.R2T2GuiMessageAnswer.fftData)
}
inline std::string* R2T2GuiMessageAnswer::_internal_mutable_fftdata() {
  _has_bits_[0] |= 0x00000002u;
  return fftdata_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* R2T2GuiMessageAnswer::release_fftdata() {
  // @@protoc_insertion_point(field_release:R2T2GuiProto.R2T2GuiMessageAnswer.fftData)
  if (!_internal_has_fftdata()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return fftdata_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void R2T2GuiMessageAnswer::set_allocated_fftdata(std::string* fftdata) {
  if (fftdata != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  fftdata_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fftdata);
  // @@protoc_insertion_point(field_set_allocated:R2T2GuiProto.R2T2GuiMessageAnswer.fftData)
}

// optional uint32 txDataAck = 4;
inline bool R2T2GuiMessageAnswer::_internal_has_txdataack() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool R2T2GuiMessageAnswer::has_txdataack() const {
  return _internal_has_txdataack();
}
inline void R2T2GuiMessageAnswer::clear_txdataack() {
  txdataack_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessageAnswer::_internal_txdataack() const {
  return txdataack_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessageAnswer::txdataack() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessageAnswer.txDataAck)
  return _internal_txdataack();
}
inline void R2T2GuiMessageAnswer::_internal_set_txdataack(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  txdataack_ = value;
}
inline void R2T2GuiMessageAnswer::set_txdataack(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_txdataack(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessageAnswer.txDataAck)
}

// optional double rssi = 5;
inline bool R2T2GuiMessageAnswer::_internal_has_rssi() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool R2T2GuiMessageAnswer::has_rssi() const {
  return _internal_has_rssi();
}
inline void R2T2GuiMessageAnswer::clear_rssi() {
  rssi_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double R2T2GuiMessageAnswer::_internal_rssi() const {
  return rssi_;
}
inline double R2T2GuiMessageAnswer::rssi() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessageAnswer.rssi)
  return _internal_rssi();
}
inline void R2T2GuiMessageAnswer::_internal_set_rssi(double value) {
  _has_bits_[0] |= 0x00000020u;
  rssi_ = value;
}
inline void R2T2GuiMessageAnswer::set_rssi(double value) {
  _internal_set_rssi(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessageAnswer.rssi)
}

// optional string version = 6;
inline bool R2T2GuiMessageAnswer::_internal_has_version() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool R2T2GuiMessageAnswer::has_version() const {
  return _internal_has_version();
}
inline void R2T2GuiMessageAnswer::clear_version() {
  version_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& R2T2GuiMessageAnswer::version() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessageAnswer.version)
  return _internal_version();
}
inline void R2T2GuiMessageAnswer::set_version(const std::string& value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessageAnswer.version)
}
inline std::string* R2T2GuiMessageAnswer::mutable_version() {
  // @@protoc_insertion_point(field_mutable:R2T2GuiProto.R2T2GuiMessageAnswer.version)
  return _internal_mutable_version();
}
inline const std::string& R2T2GuiMessageAnswer::_internal_version() const {
  return version_.GetNoArena();
}
inline void R2T2GuiMessageAnswer::_internal_set_version(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void R2T2GuiMessageAnswer::set_version(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  version_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:R2T2GuiProto.R2T2GuiMessageAnswer.version)
}
inline void R2T2GuiMessageAnswer::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:R2T2GuiProto.R2T2GuiMessageAnswer.version)
}
inline void R2T2GuiMessageAnswer::set_version(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:R2T2GuiProto.R2T2GuiMessageAnswer.version)
}
inline std::string* R2T2GuiMessageAnswer::_internal_mutable_version() {
  _has_bits_[0] |= 0x00000004u;
  return version_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* R2T2GuiMessageAnswer::release_version() {
  // @@protoc_insertion_point(field_release:R2T2GuiProto.R2T2GuiMessageAnswer.version)
  if (!_internal_has_version()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return version_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void R2T2GuiMessageAnswer::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  version_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:R2T2GuiProto.R2T2GuiMessageAnswer.version)
}

// optional uint32 fftRate = 7;
inline bool R2T2GuiMessageAnswer::_internal_has_fftrate() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool R2T2GuiMessageAnswer::has_fftrate() const {
  return _internal_has_fftrate();
}
inline void R2T2GuiMessageAnswer::clear_fftrate() {
  fftrate_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessageAnswer::_internal_fftrate() const {
  return fftrate_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 R2T2GuiMessageAnswer::fftrate() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessageAnswer.fftRate)
  return _internal_fftrate();
}
inline void R2T2GuiMessageAnswer::_internal_set_fftrate(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  fftrate_ = value;
}
inline void R2T2GuiMessageAnswer::set_fftrate(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_fftrate(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessageAnswer.fftRate)
}

// optional int32 gain = 8;
inline bool R2T2GuiMessageAnswer::_internal_has_gain() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool R2T2GuiMessageAnswer::has_gain() const {
  return _internal_has_gain();
}
inline void R2T2GuiMessageAnswer::clear_gain() {
  gain_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessageAnswer::_internal_gain() const {
  return gain_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 R2T2GuiMessageAnswer::gain() const {
  // @@protoc_insertion_point(field_get:R2T2GuiProto.R2T2GuiMessageAnswer.gain)
  return _internal_gain();
}
inline void R2T2GuiMessageAnswer::_internal_set_gain(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000080u;
  gain_ = value;
}
inline void R2T2GuiMessageAnswer::set_gain(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_gain(value);
  // @@protoc_insertion_point(field_set:R2T2GuiProto.R2T2GuiMessageAnswer.gain)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace R2T2GuiProto

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::R2T2GuiProto::R2T2GuiMessage_Command> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::R2T2GuiProto::R2T2GuiMessage_Command>() {
  return ::R2T2GuiProto::R2T2GuiMessage_Command_descriptor();
}
template <> struct is_proto_enum< ::R2T2GuiProto::R2T2GuiMessage_Mode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::R2T2GuiProto::R2T2GuiMessage_Mode>() {
  return ::R2T2GuiProto::R2T2GuiMessage_Mode_descriptor();
}
template <> struct is_proto_enum< ::R2T2GuiProto::R2T2GuiMessage_AGC> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::R2T2GuiProto::R2T2GuiMessage_AGC>() {
  return ::R2T2GuiProto::R2T2GuiMessage_AGC_descriptor();
}
template <> struct is_proto_enum< ::R2T2GuiProto::R2T2GuiMessageAnswer_Command> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::R2T2GuiProto::R2T2GuiMessageAnswer_Command>() {
  return ::R2T2GuiProto::R2T2GuiMessageAnswer_Command_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_r2t2gui_2eproto
