// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: r2t2.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "r2t2.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace R2T2Proto {

namespace {

const ::google::protobuf::Descriptor* R2T2Message_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  R2T2Message_reflection_ = NULL;
const ::google::protobuf::Descriptor* R2T2Message_Gain_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  R2T2Message_Gain_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* R2T2Message_Command_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_r2t2_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_r2t2_2eproto() {
  protobuf_AddDesc_r2t2_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "r2t2.proto");
  GOOGLE_CHECK(file != NULL);
  R2T2Message_descriptor_ = file->message_type(0);
  static const int R2T2Message_offsets_[18] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, command_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, rxdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, txdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, fftdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, txdataack_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, rxfreq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, txfreq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, txrate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, rxrate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, fftrate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, fftsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, rx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, tx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, gain_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, att_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, antenna_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, forwardpower_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, backwardpower_),
  };
  R2T2Message_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      R2T2Message_descriptor_,
      R2T2Message::internal_default_instance(),
      R2T2Message_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, _has_bits_),
      -1,
      -1,
      sizeof(R2T2Message),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message, _internal_metadata_));
  R2T2Message_Gain_descriptor_ = R2T2Message_descriptor_->nested_type(0);
  static const int R2T2Message_Gain_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message_Gain, adc_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message_Gain, gain_),
  };
  R2T2Message_Gain_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      R2T2Message_Gain_descriptor_,
      R2T2Message_Gain::internal_default_instance(),
      R2T2Message_Gain_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message_Gain, _has_bits_),
      -1,
      -1,
      sizeof(R2T2Message_Gain),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2T2Message_Gain, _internal_metadata_));
  R2T2Message_Command_descriptor_ = R2T2Message_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_r2t2_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      R2T2Message_descriptor_, R2T2Message::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      R2T2Message_Gain_descriptor_, R2T2Message_Gain::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_r2t2_2eproto() {
  R2T2Message_default_instance_.Shutdown();
  delete R2T2Message_reflection_;
  R2T2Message_Gain_default_instance_.Shutdown();
  delete R2T2Message_Gain_reflection_;
}

void protobuf_InitDefaults_r2t2_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  R2T2Message_default_instance_.DefaultConstruct();
  R2T2Message_Gain_default_instance_.DefaultConstruct();
  R2T2Message_default_instance_.get_mutable()->InitAsDefaultInstance();
  R2T2Message_Gain_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_r2t2_2eproto_once_);
void protobuf_InitDefaults_r2t2_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_r2t2_2eproto_once_,
                 &protobuf_InitDefaults_r2t2_2eproto_impl);
}
void protobuf_AddDesc_r2t2_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_r2t2_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nr2t2.proto\022\tR2T2Proto\"\350\004\n\013R2T2Message\022"
    "/\n\007command\030\001 \001(\0162\036.R2T2Proto.R2T2Message"
    ".Command\022\016\n\006rxData\030\002 \001(\014\022\016\n\006txData\030\003 \001(\014"
    "\022\017\n\007fftData\030\004 \001(\014\022\021\n\ttxDataAck\030\n \001(\r\022\016\n\006"
    "rxFreq\030\024 \001(\004\022\016\n\006txFreq\030\025 \001(\004\022\016\n\006txRate\030\026"
    " \001(\r\022\016\n\006rxRate\030\027 \001(\r\022\017\n\007fftRate\030\030 \001(\r\022\017\n"
    "\007fftSize\030\031 \001(\r\022\n\n\002rx\030\036 \001(\r\022\n\n\002tx\030\037 \001(\r\022)"
    "\n\004gain\030( \001(\0132\033.R2T2Proto.R2T2Message.Gai"
    "n\022(\n\003att\030) \001(\0132\033.R2T2Proto.R2T2Message.G"
    "ain\022\017\n\007antenna\030* \001(\r\022\024\n\014forwardPower\0302 \001"
    "(\001\022\025\n\rbackwardPower\0303 \001(\001\032!\n\004Gain\022\013\n\003adc"
    "\030\001 \002(\r\022\014\n\004gain\030\002 \002(\021\"\263\001\n\007Command\022\010\n\004NONE"
    "\020\000\022\n\n\006RXOPEN\020\001\022\n\n\006TXOPEN\020\002\022\t\n\005CLOSE\020\004\022\016\n"
    "\nSTARTAUDIO\020\005\022\r\n\tSTOPAUDIO\020\006\022\014\n\010STARTFFT"
    "\020\007\022\013\n\007STOPFFT\020\010\022\n\n\006REQFFT\020\t\022\n\n\006REINIT\020\n\022"
    "\007\n\003ACK\020\013\022\010\n\004NACK\020\014\022\013\n\007TIMEOUT\020\r\022\t\n\005ALIVE"
    "\020\016", 642);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "r2t2.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_r2t2_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_r2t2_2eproto_once_);
void protobuf_AddDesc_r2t2_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_r2t2_2eproto_once_,
                 &protobuf_AddDesc_r2t2_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_r2t2_2eproto {
  StaticDescriptorInitializer_r2t2_2eproto() {
    protobuf_AddDesc_r2t2_2eproto();
  }
} static_descriptor_initializer_r2t2_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

const ::google::protobuf::EnumDescriptor* R2T2Message_Command_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return R2T2Message_Command_descriptor_;
}
bool R2T2Message_Command_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const R2T2Message_Command R2T2Message::NONE;
const R2T2Message_Command R2T2Message::RXOPEN;
const R2T2Message_Command R2T2Message::TXOPEN;
const R2T2Message_Command R2T2Message::CLOSE;
const R2T2Message_Command R2T2Message::STARTAUDIO;
const R2T2Message_Command R2T2Message::STOPAUDIO;
const R2T2Message_Command R2T2Message::STARTFFT;
const R2T2Message_Command R2T2Message::STOPFFT;
const R2T2Message_Command R2T2Message::REQFFT;
const R2T2Message_Command R2T2Message::REINIT;
const R2T2Message_Command R2T2Message::ACK;
const R2T2Message_Command R2T2Message::NACK;
const R2T2Message_Command R2T2Message::TIMEOUT;
const R2T2Message_Command R2T2Message::ALIVE;
const R2T2Message_Command R2T2Message::Command_MIN;
const R2T2Message_Command R2T2Message::Command_MAX;
const int R2T2Message::Command_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int R2T2Message_Gain::kAdcFieldNumber;
const int R2T2Message_Gain::kGainFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

R2T2Message_Gain::R2T2Message_Gain()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_r2t2_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:R2T2Proto.R2T2Message.Gain)
}

void R2T2Message_Gain::InitAsDefaultInstance() {
}

R2T2Message_Gain::R2T2Message_Gain(const R2T2Message_Gain& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:R2T2Proto.R2T2Message.Gain)
}

void R2T2Message_Gain::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&adc_, 0, reinterpret_cast<char*>(&gain_) -
    reinterpret_cast<char*>(&adc_) + sizeof(gain_));
}

R2T2Message_Gain::~R2T2Message_Gain() {
  // @@protoc_insertion_point(destructor:R2T2Proto.R2T2Message.Gain)
  SharedDtor();
}

void R2T2Message_Gain::SharedDtor() {
}

void R2T2Message_Gain::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* R2T2Message_Gain::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return R2T2Message_Gain_descriptor_;
}

const R2T2Message_Gain& R2T2Message_Gain::default_instance() {
  protobuf_InitDefaults_r2t2_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<R2T2Message_Gain> R2T2Message_Gain_default_instance_;

R2T2Message_Gain* R2T2Message_Gain::New(::google::protobuf::Arena* arena) const {
  R2T2Message_Gain* n = new R2T2Message_Gain;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void R2T2Message_Gain::Clear() {
// @@protoc_insertion_point(message_clear_start:R2T2Proto.R2T2Message.Gain)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(R2T2Message_Gain, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<R2T2Message_Gain*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&(first), 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(adc_, gain_);

#undef ZR_HELPER_
#undef ZR_

  _has_bits_.Clear();
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool R2T2Message_Gain::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:R2T2Proto.R2T2Message.Gain)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 adc = 1;
      case 1: {
        if (tag == 8) {
          set_has_adc();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &adc_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_gain;
        break;
      }

      // required sint32 gain = 2;
      case 2: {
        if (tag == 16) {
         parse_gain:
          set_has_gain();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &gain_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:R2T2Proto.R2T2Message.Gain)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:R2T2Proto.R2T2Message.Gain)
  return false;
#undef DO_
}

void R2T2Message_Gain::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:R2T2Proto.R2T2Message.Gain)
  // required uint32 adc = 1;
  if (has_adc()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->adc(), output);
  }

  // required sint32 gain = 2;
  if (has_gain()) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(2, this->gain(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:R2T2Proto.R2T2Message.Gain)
}

::google::protobuf::uint8* R2T2Message_Gain::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:R2T2Proto.R2T2Message.Gain)
  // required uint32 adc = 1;
  if (has_adc()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->adc(), target);
  }

  // required sint32 gain = 2;
  if (has_gain()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(2, this->gain(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:R2T2Proto.R2T2Message.Gain)
  return target;
}

size_t R2T2Message_Gain::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:R2T2Proto.R2T2Message.Gain)
  size_t total_size = 0;

  if (has_adc()) {
    // required uint32 adc = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->adc());
  }

  if (has_gain()) {
    // required sint32 gain = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->gain());
  }

  return total_size;
}
size_t R2T2Message_Gain::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:R2T2Proto.R2T2Message.Gain)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required uint32 adc = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->adc());

    // required sint32 gain = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->gain());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void R2T2Message_Gain::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:R2T2Proto.R2T2Message.Gain)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const R2T2Message_Gain* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const R2T2Message_Gain>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:R2T2Proto.R2T2Message.Gain)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:R2T2Proto.R2T2Message.Gain)
    UnsafeMergeFrom(*source);
  }
}

void R2T2Message_Gain::MergeFrom(const R2T2Message_Gain& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:R2T2Proto.R2T2Message.Gain)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void R2T2Message_Gain::UnsafeMergeFrom(const R2T2Message_Gain& from) {
  GOOGLE_DCHECK(&from != this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_adc()) {
      set_adc(from.adc());
    }
    if (from.has_gain()) {
      set_gain(from.gain());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::UnknownFieldSet::MergeToInternalMetdata(
      from.unknown_fields(), &_internal_metadata_);
  }
}

void R2T2Message_Gain::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:R2T2Proto.R2T2Message.Gain)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void R2T2Message_Gain::CopyFrom(const R2T2Message_Gain& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:R2T2Proto.R2T2Message.Gain)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool R2T2Message_Gain::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void R2T2Message_Gain::Swap(R2T2Message_Gain* other) {
  if (other == this) return;
  InternalSwap(other);
}
void R2T2Message_Gain::InternalSwap(R2T2Message_Gain* other) {
  std::swap(adc_, other->adc_);
  std::swap(gain_, other->gain_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata R2T2Message_Gain::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = R2T2Message_Gain_descriptor_;
  metadata.reflection = R2T2Message_Gain_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int R2T2Message::kCommandFieldNumber;
const int R2T2Message::kRxDataFieldNumber;
const int R2T2Message::kTxDataFieldNumber;
const int R2T2Message::kFftDataFieldNumber;
const int R2T2Message::kTxDataAckFieldNumber;
const int R2T2Message::kRxFreqFieldNumber;
const int R2T2Message::kTxFreqFieldNumber;
const int R2T2Message::kTxRateFieldNumber;
const int R2T2Message::kRxRateFieldNumber;
const int R2T2Message::kFftRateFieldNumber;
const int R2T2Message::kFftSizeFieldNumber;
const int R2T2Message::kRxFieldNumber;
const int R2T2Message::kTxFieldNumber;
const int R2T2Message::kGainFieldNumber;
const int R2T2Message::kAttFieldNumber;
const int R2T2Message::kAntennaFieldNumber;
const int R2T2Message::kForwardPowerFieldNumber;
const int R2T2Message::kBackwardPowerFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

R2T2Message::R2T2Message()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_r2t2_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:R2T2Proto.R2T2Message)
}

void R2T2Message::InitAsDefaultInstance() {
  gain_ = const_cast< ::R2T2Proto::R2T2Message_Gain*>(
      ::R2T2Proto::R2T2Message_Gain::internal_default_instance());
  att_ = const_cast< ::R2T2Proto::R2T2Message_Gain*>(
      ::R2T2Proto::R2T2Message_Gain::internal_default_instance());
}

R2T2Message::R2T2Message(const R2T2Message& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:R2T2Proto.R2T2Message)
}

void R2T2Message::SharedCtor() {
  _cached_size_ = 0;
  rxdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  txdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fftdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gain_ = NULL;
  att_ = NULL;
  ::memset(&command_, 0, reinterpret_cast<char*>(&antenna_) -
    reinterpret_cast<char*>(&command_) + sizeof(antenna_));
}

R2T2Message::~R2T2Message() {
  // @@protoc_insertion_point(destructor:R2T2Proto.R2T2Message)
  SharedDtor();
}

void R2T2Message::SharedDtor() {
  rxdata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  txdata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fftdata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != &R2T2Message_default_instance_.get()) {
    delete gain_;
    delete att_;
  }
}

void R2T2Message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* R2T2Message::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return R2T2Message_descriptor_;
}

const R2T2Message& R2T2Message::default_instance() {
  protobuf_InitDefaults_r2t2_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<R2T2Message> R2T2Message_default_instance_;

R2T2Message* R2T2Message::New(::google::protobuf::Arena* arena) const {
  R2T2Message* n = new R2T2Message;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void R2T2Message::Clear() {
// @@protoc_insertion_point(message_clear_start:R2T2Proto.R2T2Message)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(R2T2Message, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<R2T2Message*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&(first), 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 255u) {
    ZR_(command_, txrate_);
    if (has_rxdata()) {
      rxdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_txdata()) {
      txdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_fftdata()) {
      fftdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  if (_has_bits_[8 / 32] & 65280u) {
    ZR_(rxrate_, tx_);
    if (has_gain()) {
      if (gain_ != NULL) gain_->::R2T2Proto::R2T2Message_Gain::Clear();
    }
    if (has_att()) {
      if (att_ != NULL) att_->::R2T2Proto::R2T2Message_Gain::Clear();
    }
    antenna_ = 0u;
  }
  ZR_(forwardpower_, backwardpower_);

#undef ZR_HELPER_
#undef ZR_

  _has_bits_.Clear();
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool R2T2Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:R2T2Proto.R2T2Message)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .R2T2Proto.R2T2Message.Command command = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::R2T2Proto::R2T2Message_Command_IsValid(value)) {
            set_command(static_cast< ::R2T2Proto::R2T2Message_Command >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_rxData;
        break;
      }

      // optional bytes rxData = 2;
      case 2: {
        if (tag == 18) {
         parse_rxData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_rxdata()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_txData;
        break;
      }

      // optional bytes txData = 3;
      case 3: {
        if (tag == 26) {
         parse_txData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_txdata()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_fftData;
        break;
      }

      // optional bytes fftData = 4;
      case 4: {
        if (tag == 34) {
         parse_fftData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_fftdata()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_txDataAck;
        break;
      }

      // optional uint32 txDataAck = 10;
      case 10: {
        if (tag == 80) {
         parse_txDataAck:
          set_has_txdataack();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &txdataack_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(160)) goto parse_rxFreq;
        break;
      }

      // optional uint64 rxFreq = 20;
      case 20: {
        if (tag == 160) {
         parse_rxFreq:
          set_has_rxfreq();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &rxfreq_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(168)) goto parse_txFreq;
        break;
      }

      // optional uint64 txFreq = 21;
      case 21: {
        if (tag == 168) {
         parse_txFreq:
          set_has_txfreq();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &txfreq_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(176)) goto parse_txRate;
        break;
      }

      // optional uint32 txRate = 22;
      case 22: {
        if (tag == 176) {
         parse_txRate:
          set_has_txrate();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &txrate_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(184)) goto parse_rxRate;
        break;
      }

      // optional uint32 rxRate = 23;
      case 23: {
        if (tag == 184) {
         parse_rxRate:
          set_has_rxrate();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &rxrate_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(192)) goto parse_fftRate;
        break;
      }

      // optional uint32 fftRate = 24;
      case 24: {
        if (tag == 192) {
         parse_fftRate:
          set_has_fftrate();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &fftrate_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(200)) goto parse_fftSize;
        break;
      }

      // optional uint32 fftSize = 25;
      case 25: {
        if (tag == 200) {
         parse_fftSize:
          set_has_fftsize();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &fftsize_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(240)) goto parse_rx;
        break;
      }

      // optional uint32 rx = 30;
      case 30: {
        if (tag == 240) {
         parse_rx:
          set_has_rx();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &rx_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(248)) goto parse_tx;
        break;
      }

      // optional uint32 tx = 31;
      case 31: {
        if (tag == 248) {
         parse_tx:
          set_has_tx();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &tx_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(322)) goto parse_gain;
        break;
      }

      // optional .R2T2Proto.R2T2Message.Gain gain = 40;
      case 40: {
        if (tag == 322) {
         parse_gain:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_gain()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(330)) goto parse_att;
        break;
      }

      // optional .R2T2Proto.R2T2Message.Gain att = 41;
      case 41: {
        if (tag == 330) {
         parse_att:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_att()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(336)) goto parse_antenna;
        break;
      }

      // optional uint32 antenna = 42;
      case 42: {
        if (tag == 336) {
         parse_antenna:
          set_has_antenna();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &antenna_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(401)) goto parse_forwardPower;
        break;
      }

      // optional double forwardPower = 50;
      case 50: {
        if (tag == 401) {
         parse_forwardPower:
          set_has_forwardpower();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &forwardpower_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(409)) goto parse_backwardPower;
        break;
      }

      // optional double backwardPower = 51;
      case 51: {
        if (tag == 409) {
         parse_backwardPower:
          set_has_backwardpower();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &backwardpower_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:R2T2Proto.R2T2Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:R2T2Proto.R2T2Message)
  return false;
#undef DO_
}

void R2T2Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:R2T2Proto.R2T2Message)
  // optional .R2T2Proto.R2T2Message.Command command = 1;
  if (has_command()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->command(), output);
  }

  // optional bytes rxData = 2;
  if (has_rxdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->rxdata(), output);
  }

  // optional bytes txData = 3;
  if (has_txdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->txdata(), output);
  }

  // optional bytes fftData = 4;
  if (has_fftdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->fftdata(), output);
  }

  // optional uint32 txDataAck = 10;
  if (has_txdataack()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->txdataack(), output);
  }

  // optional uint64 rxFreq = 20;
  if (has_rxfreq()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(20, this->rxfreq(), output);
  }

  // optional uint64 txFreq = 21;
  if (has_txfreq()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(21, this->txfreq(), output);
  }

  // optional uint32 txRate = 22;
  if (has_txrate()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(22, this->txrate(), output);
  }

  // optional uint32 rxRate = 23;
  if (has_rxrate()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(23, this->rxrate(), output);
  }

  // optional uint32 fftRate = 24;
  if (has_fftrate()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(24, this->fftrate(), output);
  }

  // optional uint32 fftSize = 25;
  if (has_fftsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(25, this->fftsize(), output);
  }

  // optional uint32 rx = 30;
  if (has_rx()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(30, this->rx(), output);
  }

  // optional uint32 tx = 31;
  if (has_tx()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(31, this->tx(), output);
  }

  // optional .R2T2Proto.R2T2Message.Gain gain = 40;
  if (has_gain()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      40, *this->gain_, output);
  }

  // optional .R2T2Proto.R2T2Message.Gain att = 41;
  if (has_att()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      41, *this->att_, output);
  }

  // optional uint32 antenna = 42;
  if (has_antenna()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(42, this->antenna(), output);
  }

  // optional double forwardPower = 50;
  if (has_forwardpower()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(50, this->forwardpower(), output);
  }

  // optional double backwardPower = 51;
  if (has_backwardpower()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(51, this->backwardpower(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:R2T2Proto.R2T2Message)
}

::google::protobuf::uint8* R2T2Message::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:R2T2Proto.R2T2Message)
  // optional .R2T2Proto.R2T2Message.Command command = 1;
  if (has_command()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->command(), target);
  }

  // optional bytes rxData = 2;
  if (has_rxdata()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->rxdata(), target);
  }

  // optional bytes txData = 3;
  if (has_txdata()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->txdata(), target);
  }

  // optional bytes fftData = 4;
  if (has_fftdata()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->fftdata(), target);
  }

  // optional uint32 txDataAck = 10;
  if (has_txdataack()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->txdataack(), target);
  }

  // optional uint64 rxFreq = 20;
  if (has_rxfreq()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(20, this->rxfreq(), target);
  }

  // optional uint64 txFreq = 21;
  if (has_txfreq()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(21, this->txfreq(), target);
  }

  // optional uint32 txRate = 22;
  if (has_txrate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(22, this->txrate(), target);
  }

  // optional uint32 rxRate = 23;
  if (has_rxrate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(23, this->rxrate(), target);
  }

  // optional uint32 fftRate = 24;
  if (has_fftrate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(24, this->fftrate(), target);
  }

  // optional uint32 fftSize = 25;
  if (has_fftsize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(25, this->fftsize(), target);
  }

  // optional uint32 rx = 30;
  if (has_rx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(30, this->rx(), target);
  }

  // optional uint32 tx = 31;
  if (has_tx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(31, this->tx(), target);
  }

  // optional .R2T2Proto.R2T2Message.Gain gain = 40;
  if (has_gain()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        40, *this->gain_, false, target);
  }

  // optional .R2T2Proto.R2T2Message.Gain att = 41;
  if (has_att()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        41, *this->att_, false, target);
  }

  // optional uint32 antenna = 42;
  if (has_antenna()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(42, this->antenna(), target);
  }

  // optional double forwardPower = 50;
  if (has_forwardpower()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(50, this->forwardpower(), target);
  }

  // optional double backwardPower = 51;
  if (has_backwardpower()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(51, this->backwardpower(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:R2T2Proto.R2T2Message)
  return target;
}

size_t R2T2Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:R2T2Proto.R2T2Message)
  size_t total_size = 0;

  if (_has_bits_[0 / 32] & 255u) {
    // optional .R2T2Proto.R2T2Message.Command command = 1;
    if (has_command()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->command());
    }

    // optional bytes rxData = 2;
    if (has_rxdata()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->rxdata());
    }

    // optional bytes txData = 3;
    if (has_txdata()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->txdata());
    }

    // optional bytes fftData = 4;
    if (has_fftdata()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->fftdata());
    }

    // optional uint32 txDataAck = 10;
    if (has_txdataack()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->txdataack());
    }

    // optional uint64 rxFreq = 20;
    if (has_rxfreq()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->rxfreq());
    }

    // optional uint64 txFreq = 21;
    if (has_txfreq()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->txfreq());
    }

    // optional uint32 txRate = 22;
    if (has_txrate()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->txrate());
    }

  }
  if (_has_bits_[8 / 32] & 65280u) {
    // optional uint32 rxRate = 23;
    if (has_rxrate()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->rxrate());
    }

    // optional uint32 fftRate = 24;
    if (has_fftrate()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->fftrate());
    }

    // optional uint32 fftSize = 25;
    if (has_fftsize()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->fftsize());
    }

    // optional uint32 rx = 30;
    if (has_rx()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->rx());
    }

    // optional uint32 tx = 31;
    if (has_tx()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->tx());
    }

    // optional .R2T2Proto.R2T2Message.Gain gain = 40;
    if (has_gain()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->gain_);
    }

    // optional .R2T2Proto.R2T2Message.Gain att = 41;
    if (has_att()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->att_);
    }

    // optional uint32 antenna = 42;
    if (has_antenna()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->antenna());
    }

  }
  if (_has_bits_[16 / 32] & 196608u) {
    // optional double forwardPower = 50;
    if (has_forwardpower()) {
      total_size += 2 + 8;
    }

    // optional double backwardPower = 51;
    if (has_backwardpower()) {
      total_size += 2 + 8;
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void R2T2Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:R2T2Proto.R2T2Message)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const R2T2Message* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const R2T2Message>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:R2T2Proto.R2T2Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:R2T2Proto.R2T2Message)
    UnsafeMergeFrom(*source);
  }
}

void R2T2Message::MergeFrom(const R2T2Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:R2T2Proto.R2T2Message)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void R2T2Message::UnsafeMergeFrom(const R2T2Message& from) {
  GOOGLE_DCHECK(&from != this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_command()) {
      set_command(from.command());
    }
    if (from.has_rxdata()) {
      set_has_rxdata();
      rxdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rxdata_);
    }
    if (from.has_txdata()) {
      set_has_txdata();
      txdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.txdata_);
    }
    if (from.has_fftdata()) {
      set_has_fftdata();
      fftdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fftdata_);
    }
    if (from.has_txdataack()) {
      set_txdataack(from.txdataack());
    }
    if (from.has_rxfreq()) {
      set_rxfreq(from.rxfreq());
    }
    if (from.has_txfreq()) {
      set_txfreq(from.txfreq());
    }
    if (from.has_txrate()) {
      set_txrate(from.txrate());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_rxrate()) {
      set_rxrate(from.rxrate());
    }
    if (from.has_fftrate()) {
      set_fftrate(from.fftrate());
    }
    if (from.has_fftsize()) {
      set_fftsize(from.fftsize());
    }
    if (from.has_rx()) {
      set_rx(from.rx());
    }
    if (from.has_tx()) {
      set_tx(from.tx());
    }
    if (from.has_gain()) {
      mutable_gain()->::R2T2Proto::R2T2Message_Gain::MergeFrom(from.gain());
    }
    if (from.has_att()) {
      mutable_att()->::R2T2Proto::R2T2Message_Gain::MergeFrom(from.att());
    }
    if (from.has_antenna()) {
      set_antenna(from.antenna());
    }
  }
  if (from._has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (from.has_forwardpower()) {
      set_forwardpower(from.forwardpower());
    }
    if (from.has_backwardpower()) {
      set_backwardpower(from.backwardpower());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::UnknownFieldSet::MergeToInternalMetdata(
      from.unknown_fields(), &_internal_metadata_);
  }
}

void R2T2Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:R2T2Proto.R2T2Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void R2T2Message::CopyFrom(const R2T2Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:R2T2Proto.R2T2Message)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool R2T2Message::IsInitialized() const {

  if (has_gain()) {
    if (!this->gain_->IsInitialized()) return false;
  }
  if (has_att()) {
    if (!this->att_->IsInitialized()) return false;
  }
  return true;
}

void R2T2Message::Swap(R2T2Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void R2T2Message::InternalSwap(R2T2Message* other) {
  std::swap(command_, other->command_);
  rxdata_.Swap(&other->rxdata_);
  txdata_.Swap(&other->txdata_);
  fftdata_.Swap(&other->fftdata_);
  std::swap(txdataack_, other->txdataack_);
  std::swap(rxfreq_, other->rxfreq_);
  std::swap(txfreq_, other->txfreq_);
  std::swap(txrate_, other->txrate_);
  std::swap(rxrate_, other->rxrate_);
  std::swap(fftrate_, other->fftrate_);
  std::swap(fftsize_, other->fftsize_);
  std::swap(rx_, other->rx_);
  std::swap(tx_, other->tx_);
  std::swap(gain_, other->gain_);
  std::swap(att_, other->att_);
  std::swap(antenna_, other->antenna_);
  std::swap(forwardpower_, other->forwardpower_);
  std::swap(backwardpower_, other->backwardpower_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata R2T2Message::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = R2T2Message_descriptor_;
  metadata.reflection = R2T2Message_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// R2T2Message_Gain

// required uint32 adc = 1;
bool R2T2Message_Gain::has_adc() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void R2T2Message_Gain::set_has_adc() {
  _has_bits_[0] |= 0x00000001u;
}
void R2T2Message_Gain::clear_has_adc() {
  _has_bits_[0] &= ~0x00000001u;
}
void R2T2Message_Gain::clear_adc() {
  adc_ = 0u;
  clear_has_adc();
}
::google::protobuf::uint32 R2T2Message_Gain::adc() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.Gain.adc)
  return adc_;
}
void R2T2Message_Gain::set_adc(::google::protobuf::uint32 value) {
  set_has_adc();
  adc_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.Gain.adc)
}

// required sint32 gain = 2;
bool R2T2Message_Gain::has_gain() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void R2T2Message_Gain::set_has_gain() {
  _has_bits_[0] |= 0x00000002u;
}
void R2T2Message_Gain::clear_has_gain() {
  _has_bits_[0] &= ~0x00000002u;
}
void R2T2Message_Gain::clear_gain() {
  gain_ = 0;
  clear_has_gain();
}
::google::protobuf::int32 R2T2Message_Gain::gain() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.Gain.gain)
  return gain_;
}
void R2T2Message_Gain::set_gain(::google::protobuf::int32 value) {
  set_has_gain();
  gain_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.Gain.gain)
}

inline const R2T2Message_Gain* R2T2Message_Gain::internal_default_instance() {
  return &R2T2Message_Gain_default_instance_.get();
}
// -------------------------------------------------------------------

// R2T2Message

// optional .R2T2Proto.R2T2Message.Command command = 1;
bool R2T2Message::has_command() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void R2T2Message::set_has_command() {
  _has_bits_[0] |= 0x00000001u;
}
void R2T2Message::clear_has_command() {
  _has_bits_[0] &= ~0x00000001u;
}
void R2T2Message::clear_command() {
  command_ = 0;
  clear_has_command();
}
::R2T2Proto::R2T2Message_Command R2T2Message::command() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.command)
  return static_cast< ::R2T2Proto::R2T2Message_Command >(command_);
}
void R2T2Message::set_command(::R2T2Proto::R2T2Message_Command value) {
  assert(::R2T2Proto::R2T2Message_Command_IsValid(value));
  set_has_command();
  command_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.command)
}

// optional bytes rxData = 2;
bool R2T2Message::has_rxdata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void R2T2Message::set_has_rxdata() {
  _has_bits_[0] |= 0x00000002u;
}
void R2T2Message::clear_has_rxdata() {
  _has_bits_[0] &= ~0x00000002u;
}
void R2T2Message::clear_rxdata() {
  rxdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_rxdata();
}
const ::std::string& R2T2Message::rxdata() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.rxData)
  return rxdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void R2T2Message::set_rxdata(const ::std::string& value) {
  set_has_rxdata();
  rxdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.rxData)
}
void R2T2Message::set_rxdata(const char* value) {
  set_has_rxdata();
  rxdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:R2T2Proto.R2T2Message.rxData)
}
void R2T2Message::set_rxdata(const void* value, size_t size) {
  set_has_rxdata();
  rxdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:R2T2Proto.R2T2Message.rxData)
}
::std::string* R2T2Message::mutable_rxdata() {
  set_has_rxdata();
  // @@protoc_insertion_point(field_mutable:R2T2Proto.R2T2Message.rxData)
  return rxdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* R2T2Message::release_rxdata() {
  // @@protoc_insertion_point(field_release:R2T2Proto.R2T2Message.rxData)
  clear_has_rxdata();
  return rxdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void R2T2Message::set_allocated_rxdata(::std::string* rxdata) {
  if (rxdata != NULL) {
    set_has_rxdata();
  } else {
    clear_has_rxdata();
  }
  rxdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rxdata);
  // @@protoc_insertion_point(field_set_allocated:R2T2Proto.R2T2Message.rxData)
}

// optional bytes txData = 3;
bool R2T2Message::has_txdata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void R2T2Message::set_has_txdata() {
  _has_bits_[0] |= 0x00000004u;
}
void R2T2Message::clear_has_txdata() {
  _has_bits_[0] &= ~0x00000004u;
}
void R2T2Message::clear_txdata() {
  txdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_txdata();
}
const ::std::string& R2T2Message::txdata() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.txData)
  return txdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void R2T2Message::set_txdata(const ::std::string& value) {
  set_has_txdata();
  txdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.txData)
}
void R2T2Message::set_txdata(const char* value) {
  set_has_txdata();
  txdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:R2T2Proto.R2T2Message.txData)
}
void R2T2Message::set_txdata(const void* value, size_t size) {
  set_has_txdata();
  txdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:R2T2Proto.R2T2Message.txData)
}
::std::string* R2T2Message::mutable_txdata() {
  set_has_txdata();
  // @@protoc_insertion_point(field_mutable:R2T2Proto.R2T2Message.txData)
  return txdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* R2T2Message::release_txdata() {
  // @@protoc_insertion_point(field_release:R2T2Proto.R2T2Message.txData)
  clear_has_txdata();
  return txdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void R2T2Message::set_allocated_txdata(::std::string* txdata) {
  if (txdata != NULL) {
    set_has_txdata();
  } else {
    clear_has_txdata();
  }
  txdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), txdata);
  // @@protoc_insertion_point(field_set_allocated:R2T2Proto.R2T2Message.txData)
}

// optional bytes fftData = 4;
bool R2T2Message::has_fftdata() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void R2T2Message::set_has_fftdata() {
  _has_bits_[0] |= 0x00000008u;
}
void R2T2Message::clear_has_fftdata() {
  _has_bits_[0] &= ~0x00000008u;
}
void R2T2Message::clear_fftdata() {
  fftdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_fftdata();
}
const ::std::string& R2T2Message::fftdata() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.fftData)
  return fftdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void R2T2Message::set_fftdata(const ::std::string& value) {
  set_has_fftdata();
  fftdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.fftData)
}
void R2T2Message::set_fftdata(const char* value) {
  set_has_fftdata();
  fftdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:R2T2Proto.R2T2Message.fftData)
}
void R2T2Message::set_fftdata(const void* value, size_t size) {
  set_has_fftdata();
  fftdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:R2T2Proto.R2T2Message.fftData)
}
::std::string* R2T2Message::mutable_fftdata() {
  set_has_fftdata();
  // @@protoc_insertion_point(field_mutable:R2T2Proto.R2T2Message.fftData)
  return fftdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* R2T2Message::release_fftdata() {
  // @@protoc_insertion_point(field_release:R2T2Proto.R2T2Message.fftData)
  clear_has_fftdata();
  return fftdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void R2T2Message::set_allocated_fftdata(::std::string* fftdata) {
  if (fftdata != NULL) {
    set_has_fftdata();
  } else {
    clear_has_fftdata();
  }
  fftdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fftdata);
  // @@protoc_insertion_point(field_set_allocated:R2T2Proto.R2T2Message.fftData)
}

// optional uint32 txDataAck = 10;
bool R2T2Message::has_txdataack() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void R2T2Message::set_has_txdataack() {
  _has_bits_[0] |= 0x00000010u;
}
void R2T2Message::clear_has_txdataack() {
  _has_bits_[0] &= ~0x00000010u;
}
void R2T2Message::clear_txdataack() {
  txdataack_ = 0u;
  clear_has_txdataack();
}
::google::protobuf::uint32 R2T2Message::txdataack() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.txDataAck)
  return txdataack_;
}
void R2T2Message::set_txdataack(::google::protobuf::uint32 value) {
  set_has_txdataack();
  txdataack_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.txDataAck)
}

// optional uint64 rxFreq = 20;
bool R2T2Message::has_rxfreq() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void R2T2Message::set_has_rxfreq() {
  _has_bits_[0] |= 0x00000020u;
}
void R2T2Message::clear_has_rxfreq() {
  _has_bits_[0] &= ~0x00000020u;
}
void R2T2Message::clear_rxfreq() {
  rxfreq_ = GOOGLE_ULONGLONG(0);
  clear_has_rxfreq();
}
::google::protobuf::uint64 R2T2Message::rxfreq() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.rxFreq)
  return rxfreq_;
}
void R2T2Message::set_rxfreq(::google::protobuf::uint64 value) {
  set_has_rxfreq();
  rxfreq_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.rxFreq)
}

// optional uint64 txFreq = 21;
bool R2T2Message::has_txfreq() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void R2T2Message::set_has_txfreq() {
  _has_bits_[0] |= 0x00000040u;
}
void R2T2Message::clear_has_txfreq() {
  _has_bits_[0] &= ~0x00000040u;
}
void R2T2Message::clear_txfreq() {
  txfreq_ = GOOGLE_ULONGLONG(0);
  clear_has_txfreq();
}
::google::protobuf::uint64 R2T2Message::txfreq() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.txFreq)
  return txfreq_;
}
void R2T2Message::set_txfreq(::google::protobuf::uint64 value) {
  set_has_txfreq();
  txfreq_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.txFreq)
}

// optional uint32 txRate = 22;
bool R2T2Message::has_txrate() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void R2T2Message::set_has_txrate() {
  _has_bits_[0] |= 0x00000080u;
}
void R2T2Message::clear_has_txrate() {
  _has_bits_[0] &= ~0x00000080u;
}
void R2T2Message::clear_txrate() {
  txrate_ = 0u;
  clear_has_txrate();
}
::google::protobuf::uint32 R2T2Message::txrate() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.txRate)
  return txrate_;
}
void R2T2Message::set_txrate(::google::protobuf::uint32 value) {
  set_has_txrate();
  txrate_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.txRate)
}

// optional uint32 rxRate = 23;
bool R2T2Message::has_rxrate() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void R2T2Message::set_has_rxrate() {
  _has_bits_[0] |= 0x00000100u;
}
void R2T2Message::clear_has_rxrate() {
  _has_bits_[0] &= ~0x00000100u;
}
void R2T2Message::clear_rxrate() {
  rxrate_ = 0u;
  clear_has_rxrate();
}
::google::protobuf::uint32 R2T2Message::rxrate() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.rxRate)
  return rxrate_;
}
void R2T2Message::set_rxrate(::google::protobuf::uint32 value) {
  set_has_rxrate();
  rxrate_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.rxRate)
}

// optional uint32 fftRate = 24;
bool R2T2Message::has_fftrate() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void R2T2Message::set_has_fftrate() {
  _has_bits_[0] |= 0x00000200u;
}
void R2T2Message::clear_has_fftrate() {
  _has_bits_[0] &= ~0x00000200u;
}
void R2T2Message::clear_fftrate() {
  fftrate_ = 0u;
  clear_has_fftrate();
}
::google::protobuf::uint32 R2T2Message::fftrate() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.fftRate)
  return fftrate_;
}
void R2T2Message::set_fftrate(::google::protobuf::uint32 value) {
  set_has_fftrate();
  fftrate_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.fftRate)
}

// optional uint32 fftSize = 25;
bool R2T2Message::has_fftsize() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void R2T2Message::set_has_fftsize() {
  _has_bits_[0] |= 0x00000400u;
}
void R2T2Message::clear_has_fftsize() {
  _has_bits_[0] &= ~0x00000400u;
}
void R2T2Message::clear_fftsize() {
  fftsize_ = 0u;
  clear_has_fftsize();
}
::google::protobuf::uint32 R2T2Message::fftsize() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.fftSize)
  return fftsize_;
}
void R2T2Message::set_fftsize(::google::protobuf::uint32 value) {
  set_has_fftsize();
  fftsize_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.fftSize)
}

// optional uint32 rx = 30;
bool R2T2Message::has_rx() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
void R2T2Message::set_has_rx() {
  _has_bits_[0] |= 0x00000800u;
}
void R2T2Message::clear_has_rx() {
  _has_bits_[0] &= ~0x00000800u;
}
void R2T2Message::clear_rx() {
  rx_ = 0u;
  clear_has_rx();
}
::google::protobuf::uint32 R2T2Message::rx() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.rx)
  return rx_;
}
void R2T2Message::set_rx(::google::protobuf::uint32 value) {
  set_has_rx();
  rx_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.rx)
}

// optional uint32 tx = 31;
bool R2T2Message::has_tx() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
void R2T2Message::set_has_tx() {
  _has_bits_[0] |= 0x00001000u;
}
void R2T2Message::clear_has_tx() {
  _has_bits_[0] &= ~0x00001000u;
}
void R2T2Message::clear_tx() {
  tx_ = 0u;
  clear_has_tx();
}
::google::protobuf::uint32 R2T2Message::tx() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.tx)
  return tx_;
}
void R2T2Message::set_tx(::google::protobuf::uint32 value) {
  set_has_tx();
  tx_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.tx)
}

// optional .R2T2Proto.R2T2Message.Gain gain = 40;
bool R2T2Message::has_gain() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
void R2T2Message::set_has_gain() {
  _has_bits_[0] |= 0x00002000u;
}
void R2T2Message::clear_has_gain() {
  _has_bits_[0] &= ~0x00002000u;
}
void R2T2Message::clear_gain() {
  if (gain_ != NULL) gain_->::R2T2Proto::R2T2Message_Gain::Clear();
  clear_has_gain();
}
const ::R2T2Proto::R2T2Message_Gain& R2T2Message::gain() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.gain)
  return gain_ != NULL ? *gain_
                         : *::R2T2Proto::R2T2Message_Gain::internal_default_instance();
}
::R2T2Proto::R2T2Message_Gain* R2T2Message::mutable_gain() {
  set_has_gain();
  if (gain_ == NULL) {
    gain_ = new ::R2T2Proto::R2T2Message_Gain;
  }
  // @@protoc_insertion_point(field_mutable:R2T2Proto.R2T2Message.gain)
  return gain_;
}
::R2T2Proto::R2T2Message_Gain* R2T2Message::release_gain() {
  // @@protoc_insertion_point(field_release:R2T2Proto.R2T2Message.gain)
  clear_has_gain();
  ::R2T2Proto::R2T2Message_Gain* temp = gain_;
  gain_ = NULL;
  return temp;
}
void R2T2Message::set_allocated_gain(::R2T2Proto::R2T2Message_Gain* gain) {
  delete gain_;
  gain_ = gain;
  if (gain) {
    set_has_gain();
  } else {
    clear_has_gain();
  }
  // @@protoc_insertion_point(field_set_allocated:R2T2Proto.R2T2Message.gain)
}

// optional .R2T2Proto.R2T2Message.Gain att = 41;
bool R2T2Message::has_att() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
void R2T2Message::set_has_att() {
  _has_bits_[0] |= 0x00004000u;
}
void R2T2Message::clear_has_att() {
  _has_bits_[0] &= ~0x00004000u;
}
void R2T2Message::clear_att() {
  if (att_ != NULL) att_->::R2T2Proto::R2T2Message_Gain::Clear();
  clear_has_att();
}
const ::R2T2Proto::R2T2Message_Gain& R2T2Message::att() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.att)
  return att_ != NULL ? *att_
                         : *::R2T2Proto::R2T2Message_Gain::internal_default_instance();
}
::R2T2Proto::R2T2Message_Gain* R2T2Message::mutable_att() {
  set_has_att();
  if (att_ == NULL) {
    att_ = new ::R2T2Proto::R2T2Message_Gain;
  }
  // @@protoc_insertion_point(field_mutable:R2T2Proto.R2T2Message.att)
  return att_;
}
::R2T2Proto::R2T2Message_Gain* R2T2Message::release_att() {
  // @@protoc_insertion_point(field_release:R2T2Proto.R2T2Message.att)
  clear_has_att();
  ::R2T2Proto::R2T2Message_Gain* temp = att_;
  att_ = NULL;
  return temp;
}
void R2T2Message::set_allocated_att(::R2T2Proto::R2T2Message_Gain* att) {
  delete att_;
  att_ = att;
  if (att) {
    set_has_att();
  } else {
    clear_has_att();
  }
  // @@protoc_insertion_point(field_set_allocated:R2T2Proto.R2T2Message.att)
}

// optional uint32 antenna = 42;
bool R2T2Message::has_antenna() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
void R2T2Message::set_has_antenna() {
  _has_bits_[0] |= 0x00008000u;
}
void R2T2Message::clear_has_antenna() {
  _has_bits_[0] &= ~0x00008000u;
}
void R2T2Message::clear_antenna() {
  antenna_ = 0u;
  clear_has_antenna();
}
::google::protobuf::uint32 R2T2Message::antenna() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.antenna)
  return antenna_;
}
void R2T2Message::set_antenna(::google::protobuf::uint32 value) {
  set_has_antenna();
  antenna_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.antenna)
}

// optional double forwardPower = 50;
bool R2T2Message::has_forwardpower() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
void R2T2Message::set_has_forwardpower() {
  _has_bits_[0] |= 0x00010000u;
}
void R2T2Message::clear_has_forwardpower() {
  _has_bits_[0] &= ~0x00010000u;
}
void R2T2Message::clear_forwardpower() {
  forwardpower_ = 0;
  clear_has_forwardpower();
}
double R2T2Message::forwardpower() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.forwardPower)
  return forwardpower_;
}
void R2T2Message::set_forwardpower(double value) {
  set_has_forwardpower();
  forwardpower_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.forwardPower)
}

// optional double backwardPower = 51;
bool R2T2Message::has_backwardpower() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
void R2T2Message::set_has_backwardpower() {
  _has_bits_[0] |= 0x00020000u;
}
void R2T2Message::clear_has_backwardpower() {
  _has_bits_[0] &= ~0x00020000u;
}
void R2T2Message::clear_backwardpower() {
  backwardpower_ = 0;
  clear_has_backwardpower();
}
double R2T2Message::backwardpower() const {
  // @@protoc_insertion_point(field_get:R2T2Proto.R2T2Message.backwardPower)
  return backwardpower_;
}
void R2T2Message::set_backwardpower(double value) {
  set_has_backwardpower();
  backwardpower_ = value;
  // @@protoc_insertion_point(field_set:R2T2Proto.R2T2Message.backwardPower)
}

inline const R2T2Message* R2T2Message::internal_default_instance() {
  return &R2T2Message_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace R2T2Proto

// @@protoc_insertion_point(global_scope)
